- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Import VPC Variables
      include_vars:
        file: vars/vpc_setup.txt
      
    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr}}"
        region: "{{ region }}"
        state: "{{ state }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout

#    - debug:
#        var: vpcout

    - name: Create Public Subnet 1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create Public Subnet 2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub2Cidr }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub3Cidr }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out