- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Import VPC Variables
      include_vars:
        file: vars/vpc_setup.txt
      
    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr}}"
        region: "{{ region }}"
        state: "{{ state }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout

#    - debug:
#        var: vpcout

    - name: Create Public Subnet 1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create Public Subnet 2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub2Cidr }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub3Cidr }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out
    
    - name: Create Private subnet 1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSub1Cidr }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub1
      register: privsub1_out

    - name: Create Private subnet 2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSub2Cidr }}"
        az: "{{ zone2}}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub2
      register: privsub2_out
    
    - name: Create Private subnet 3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSub3Cidr }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-PrivSub3
      register: PrivSub3_out

    - name: Internet Gatewaty setup
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: vprofile_IGW
      register: igw_out 

    - debug:
       var: igw_out

    - name: Setup up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: pubRT_out